### ISSUE TITLE
Plz help

### ISSUE THREAD

**Issue by Sanketjr30** [dhananjaymenon/SpeedRadar-OpenCV-#5]
What if I want these to work on diff videos will it work does it requires training or just need to make changes in given code like roi n speed (Also how to set speed for diff vid) ..
Plz help my final presentation of BE project is on 2 June it's urgent 🙏🙏

**Comment by dhananjaymenon** [comment]
Changes to some of the numbers in the code will have to be made for a different video. Training will not be required (as this does not use AI). The logic behind detecting vehicles is through image subtraction between frames.

Also note that the red lines are horizontal as the camera is right above the road. With other angles (like side angles) the calculation of speed gets complicated.

**Comment by Sanketjr30** [comment]
Any Specific logic or formula you used to calculate speed ie: 214 .
If you could explain will be better for me to work with other video
